project:
  type: website

website:
  title: "Introduction to RStudio for Infectious Disease Modelling"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Getting Started
        href: getting_started.qmd
      - text: Introduction to R Programming
        href: intro_to_r.qmd
      - text: Starting with Data
        href: starting_with_data.qmd
      - text: Visualization with ggplot2
        href: visualization.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4
    toc-location: left

editor: visual

